version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "60s", "python", "run.py"]

    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=secret
      - DB_NAME=blogdb

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blogdb"]
      interval: 10s
      timeout: 5s
      retries: 5 

networks:
  app-network:

volumes:
  pgdata:
