version: '3.8'
services:
  scraper:
    build:
      context: .
      dockerfile: scrapper.Dockerfile
    volumes:
      - data-volume:/usr/src/scrapper/data

  streamlit-app:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    volumes:
      - data-volume:/usr/src/scrapper/data
    ports:
      - "8501:8501"

volumes:
  data-volume:
