version: '3.9'

services:
  web:
    build: .
    ports:
      - "9092:9090"
    networks:
      - my-shared-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - my-shared-network

networks:
  my-shared-network:
