version: '3.9'


services:
    web:
        build: C:\Users\La Festive\Documents\IABD5\Docker\Docker\labs\60-lab-docker-compose
        ports:
            - "9092:9090"
        networks: 
            - my-shared-network
    redis:
        image: redis:alpine
        networks: 
            - my-shared-network

networks:
    my-shared-network: