version: '3.8'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - data_volume:/app/data
  # Pour SQLite, ce volume est suffisant pour partager la base de données. 
  # Pour une base de données comme PostgreSQL, vous définiriez un service supplémentaire ici.

volumes:
  data_volume:
