version: '3.9'

services:
  web:
    build: .
    ports:
      - "9092:9090"
    networks:
      - my-shared-network
    platform: linux/amd64

  redis:
    image: redis:alpine
    networks:
      - my-shared-network
    platform: linux/amd64

networks:
  my-shared-network: